In [1]:
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# import tensorflow_probability as tfp
# from tensorflow.python.keras.models import Sequential
# from tensorflow.python.keras.layers import Dense
# from tensorflow.python.keras import optimizers
# import pandas as pd

# # データの読み込み
# path = "../data/format_data.csv"
# data = pd.read_csv(path)

# # 特徴量とターゲット
# features = [
#     "Rank","Kinryou","Nobori","Ninki",
#     "Race Number","Distance","Weight","Weight Change",
#     "Sex","Age","Ground_ダ","Ground_芝","Ground_障","Condition_不",
#     "Condition_稍","Condition_良","Condition_重","Weather_小雨","Weather_小雪",
#     "Weather_晴","Weather_曇","Weather_雨","Weather_雪"
# ]
# target = "Time_x"
# X = data[features]
# y = data[target]

# # データの標準化
# scaler = StandardScaler()
# X = scaler.fit_transform(X)

# # データの分割
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
# # データの形状に合わせた入力
# input_dim = X_train.shape[1]  # 特徴数に基づく

# # BNNのモデル定義
# tfpl = tfp.layers  # tensorflow_probabilityのレイヤーを使用

# model = Sequential([
#     Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
#     Dense(32, activation='relu'),
#     Dense(1)  # 出力は1次元（レースタイム）
# ])

# # モデルのコンパイル
# model.compile(optimizer=optimizers.RMSprop(lr=0.001), loss='mse', metrics=['mae'])

# # モデルの訓練
# model.fit(X_train, y_train, epochs=100, verbose=1)

# history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=1)

In [2]:
import keras
from keras import layers
from keras import ops

2024-11-25 23:53:09.971039: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-25 23:53:09.997376: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-25 23:53:10.207134: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-25 23:53:10.405597: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1732546390.600195   27033 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1732546390.65

In [19]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)

x = ops.ones((3, 3))
y = model(x)
(x,y)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.610035  ,  0.43316403, -0.25271648, -0.6282019 ],
        [-0.610035  ,  0.43316403, -0.25271648, -0.6282019 ],
        [-0.610035  ,  0.43316403, -0.25271648, -0.6282019 ]],
       dtype=float32)>)

In [41]:
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")
layer3 = layers.Dense(4, name="layer3")

x = ops.ones((3,3))
y = layer3(layer2(layer1(x)))
(x,y)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.24193572,  0.18014081, -0.16411881, -0.18980053],
        [-0.24193572,  0.18014081, -0.16411881, -0.18980053],
        [-0.24193572,  0.18014081, -0.16411881, -0.18980053]],
       dtype=float32)>)